version: '3'
services:
  setup-bigdawg:
    env_file: .env.sample
    build: .
    networks:
      - polyflow
  sqlpad:
    container_name: sqlpad
    image: sqlpad/sqlpad:4.1.0
    ports:
      - 5000:3000
    networks:
      - polyflow
  run-experiment:
    env_file: .env.sample
    build: .
    command: node runExperiment.js
    networks:
      - polyflow

networks:
  polyflow:
    external: true
